/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description Frontend URL to return to after login; must be in the allowed origin list */
          redirect_uri?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirects the browser to the Cognito hosted UI authorize endpoint. Sets oauth_state, oauth_nonce and oauth_redirect cookies. */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description Authorization code returned by Cognito */
          code?: string;
          /** @description Must match the oauth_state cookie set during login */
          state?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirects to the stored frontend URL on success (with a session cookie set), or to the same URL with ?error=auth_failed on failure. */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authenticated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: {
                id: string;
                email: string;
              };
            };
          };
        };
        /** @description Not authenticated */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: {
          redirect_uri?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              cognitoLogoutUrl: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recommendations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recommendation retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              recommendations: components['schemas']['Recommendation'][] | null;
              hasEmail: boolean;
              isRecurringMonthly: boolean;
              /** Format: uuid */
              requestId: string;
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description Recommendation not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
        /** @description Unable to create recommendations */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recommendations/add-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/x-www-form-urlencoded': {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            recurring?: 'true' | 'false';
          };
        };
      };
      responses: {
        /** @description Email added successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  /** @enum {boolean} */
                  success: true;
                }
              | {
                  /** @enum {boolean} */
                  success: false;
                  error: string;
                };
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  /** @enum {boolean} */
                  success: true;
                }
              | {
                  /** @enum {boolean} */
                  success: false;
                  error: string;
                };
          };
        };
        /** @description Recommendation not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  /** @enum {boolean} */
                  success: true;
                }
              | {
                  /** @enum {boolean} */
                  success: false;
                  error: string;
                };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recommendations/delete-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/x-www-form-urlencoded': {
            /** Format: uuid */
            requestId: string;
          };
        };
      };
      responses: {
        /** @description Email removed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': Record<string, never>;
          };
        };
        /** @description Validation failed */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recommendations/from-bookcase': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /**
             * Format: binary
             * @description One or more bookcase images. Multiple files can be uploaded with the same field name.
             */
            bookcase?: string;
          };
        };
      };
      responses: {
        /** @description Recommendation request created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              id: string;
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description No files uploaded */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
        /** @description Failed to queue recommendation processing */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/queue-due-recommendations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description API key for authentication */
          'x-api-key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recommendations queued successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reextract-recurring-books': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description API key for authentication */
          'x-api-key': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Books extracted for recurring users' unprocessed images */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              totalImages: number;
              processedImages: number;
              failures: number;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile/{requestId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Profile retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              images: {
                id: number;
                contentType: string;
                extractedBooks:
                  | {
                      title: string;
                      author: string | null;
                    }[]
                  | null;
                /** Format: date-time */
                processedUtc: string | null;
              }[];
              customPreferences: string | null;
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile/{requestId}/images/{imageId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
          imageId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Image retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'image/*': string;
          };
        };
        /** @description Image not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
          imageId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Image deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description Image not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile/{requestId}/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /**
             * Format: binary
             * @description One or more additional bookcase images.
             */
            bookcase?: string;
          };
        };
      };
      responses: {
        /** @description Images added and recommendations queued for regeneration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              imagesAdded: number;
              /** Format: uuid */
              recommendationId: string;
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description No files uploaded */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
        /** @description Failed to queue recommendation processing */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile/{requestId}/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/x-www-form-urlencoded': {
            customPreferences?: string;
          };
        };
      };
      responses: {
        /** @description Preferences updated and recommendations queued for regeneration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              recommendationId: string;
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description Preferences don't look like a reading preference */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
        /** @description Failed to queue recommendation processing */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/profile/{requestId}/recommendations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          requestId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recent recommendations retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              recommendations: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                createdUtc: string;
                /** Format: date-time */
                processedUtc: string | null;
              }[];
              /** @enum {boolean} */
              success: true;
            };
          };
        };
        /** @description Request not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
              /** @enum {boolean} */
              success: false;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/auth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Exchange a Cognito JWT for a long-lived MCP JWT token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description MCP JWT token generated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description JWT token for MCP authentication */
              token: string;
              /** @description User ID */
              userId: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/recipes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all recipes for the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recipes retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: components['schemas']['Recipe'];
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/recipes/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Search recipes by name, description, ingredients, or instructions */
    get: {
      parameters: {
        query: {
          /** @description Search query string */
          q: string;
          /** @description Comma-separated fields to search: name,description,ingredients,instructions */
          fields?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Search results retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Array of matching recipes */
              results: {
                /**
                 * Format: uuid
                 * @description Recipe UUID
                 */
                uuid: string;
                /** @description Recipe name */
                name: string;
                /** @description Recipe description */
                description: string;
                /** @description Flattened list of ingredient names */
                ingredients: string[];
              }[];
              /** @description Number of results returned */
              count: number;
            };
          };
        };
        /** @description Bad request - invalid query parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/recipes/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Delete a recipe for the authenticated user */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Recipe UUID to delete */
          uuid: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recipe deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Whether delete was successful */
              success: boolean;
              /**
               * Format: uuid
               * @description UUID of deleted recipe
               */
              uuid: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/meal-plan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get the meal plan for the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Meal plan retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MealPlan'];
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    /** @description Update the meal plan for the authenticated user */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['MealPlan'];
        };
      };
      responses: {
        /** @description Meal plan updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Whether update was successful */
              success: boolean;
            };
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/shopping-list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get aggregated shopping list from recipes in the meal plan, optionally filtered by date range */
    get: {
      parameters: {
        query?: {
          /** @description Array of Unix timestamps (milliseconds) to include in shopping list */
          dates?: string | string[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Shopping list retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Name of the ingredient */
              ingredient: string;
              /** @description Array of quantities with units */
              quantities: {
                /** @description Quantity value */
                value?: number;
                /** @description Unit of measurement */
                unit: string;
              }[];
              /** @description Shopping category for the ingredient */
              category: string;
              /** @description List of meals this ingredient belongs to */
              meals: string[];
            }[];
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/s3/signed-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Generate a signed GET URL for downloading files from S3 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description S3 object key */
            key: string;
          };
        };
      };
      responses: {
        /** @description Signed GET URL generated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * Format: uri
               * @description Signed GET URL valid for download
               */
              signedUrl: string;
            };
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/s3/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Generate a signed PUT URL for uploading files to S3 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Original filename */
            fileName: string;
            /** @description MIME type (e.g., "image/jpeg") */
            contentType: string;
          };
        };
      };
      responses: {
        /** @description Signed PUT URL generated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * Format: uri
               * @description Signed PUT URL valid for upload
               */
              signedUrl: string;
              /** @description S3 object key where file will be stored */
              key: string;
            };
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/s3/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Delete a file from S3 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description S3 object key to delete */
            key: string;
          };
        };
      };
      responses: {
        /** @description File deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Whether delete was successful */
              success: boolean;
            };
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mise/parse-recipe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Parse natural language recipe text and save to the user account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Natural language recipe text to parse */
            recipeText: string;
            /**
             * Format: uuid
             * @description Recipe UUID for editing existing recipes
             */
            recipeId?: string;
            /** @description S3 key of the image to associate with this recipe (from presigned upload endpoint) */
            imageKey?: string;
          };
        };
      };
      responses: {
        /** @description Recipe parsed and saved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Recipe'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tfl/stations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List every tube station and the lines that serve it. Intended to be fetched once and cached client-side rather than queried per search. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Every tube station with the lines serving it */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              stations: {
                /** @description TfL StopPoint ID */
                id: string;
                /** @description Station name */
                name: string;
                /** @description Lines serving this station */
                lines: {
                  /** @description TfL Line ID */
                  lineId: string;
                  /** @description Line name */
                  lineName: string;
                }[];
              }[];
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tfl/arrivals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get the next arrivals for a line at a station */
    get: {
      parameters: {
        query: {
          /** @description TfL StopPoint ID */
          stopPointId: string;
          /** @description TfL line ID, e.g. "victoria" */
          lineId: string;
          /** @description Maximum number of arrivals to return */
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Next arrivals for the station */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              arrivals: {
                lineId: string;
                lineName: string;
                platformName: string;
                direction: string;
                destinationName: string;
                /** @description Seconds until arrival */
                timeToStationSeconds: number;
                /** @description ISO timestamp of expected arrival */
                expectedArrival: string;
                /** @description Human-readable current position of the train, e.g. "At Green Park" */
                currentLocation: string;
              }[];
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/flights/area': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get live aircraft positions within a geographical bounding box */
    get: {
      parameters: {
        query?: {
          /** @description Southern edge of the search box */
          minLatitude?: number | null;
          /** @description Northern edge of the search box */
          maxLatitude?: number | null;
          /** @description Western edge of the search box */
          minLongitude?: number | null;
          /** @description Eastern edge of the search box */
          maxLongitude?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Aircraft currently within the bounding box */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              aircraft: {
                /** @description 24-bit ICAO transponder address, e.g. "4ca7b3" */
                icao24: string;
                /** @description Callsign currently broadcast by the aircraft */
                callsign: string | null;
                latitude: number;
                longitude: number;
                onGround: boolean;
                /** @description Barometric altitude in meters */
                altitudeMeters: number | null;
                velocityMetersPerSecond: number | null;
                /** @description True track in degrees, 0 is north */
                headingDegrees: number | null;
                verticalRateMetersPerSecond: number | null;
              }[];
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/flights/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Search for flights by flight number, e.g. to find where a specific plane is */
    get: {
      parameters: {
        query: {
          /** @description Flight number, e.g. "BA123" */
          flightNumber: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flights matching the given flight number */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              flights: {
                /** @description Opaque identifier to pass to the flight details endpoint */
                faFlightId: string;
                ident: string;
                /** @description Operating airline */
                operator: string | null;
                aircraftType: string | null;
                registration: string | null;
                origin: {
                  code: string | null;
                  name: string | null;
                  city: string | null;
                } | null;
                destination: {
                  code: string | null;
                  name: string | null;
                  city: string | null;
                } | null;
                status: string;
                scheduledOut: string | null;
                estimatedOut: string | null;
                actualOut: string | null;
                scheduledIn: string | null;
                estimatedIn: string | null;
                actualIn: string | null;
              }[];
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
        /** @description FlightAware is not configured yet */
        501: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/flights/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get full details for a specific aircraft, combining its live position with route/airline information */
    get: {
      parameters: {
        query: {
          /** @description 24-bit ICAO transponder address from the area search */
          icao24: string;
          /** @description Callsign from the area search, used to look up route/airline details */
          callsign?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Combined position and route details for the aircraft */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              icao24: string;
              callsign: string | null;
              /** @description Operating airline, from the matched route or the callsign prefix; null for non-airline callsigns */
              airline: {
                /** @description ICAO airline code, e.g. "BAW" */
                code: string;
                /** @description Airline name, null when it could not be looked up */
                name: string | null;
              } | null;
              position: {
                latitude: number;
                longitude: number;
                onGround: boolean;
                altitudeMeters: number | null;
                velocityMetersPerSecond: number | null;
                headingDegrees: number | null;
                verticalRateMetersPerSecond: number | null;
              } | null;
              /** @description Route/airline details, null when no match could be found */
              route: {
                faFlightId: string;
                /** @description ICAO code of the operating airline */
                operator: string | null;
                aircraftType: string | null;
                registration: string | null;
                origin: {
                  code: string | null;
                  name: string | null;
                  city: string | null;
                } | null;
                destination: {
                  code: string | null;
                  name: string | null;
                  city: string | null;
                } | null;
                status: string;
                scheduledOut: string | null;
                estimatedOut: string | null;
                actualOut: string | null;
                scheduledIn: string | null;
                estimatedIn: string | null;
                actualIn: string | null;
              } | null;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/flights/photo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get a photo of a specific aircraft from Planespotters.net, with its attribution */
    get: {
      parameters: {
        query: {
          /** @description 24-bit ICAO transponder address from the area search */
          icao24: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The aircraft photo, or null when none is available */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description A photo of this exact aircraft, null when none is available */
              photo: {
                /** @description Image URL, hosted by Planespotters.net */
                url: string;
                width: number;
                height: number;
                /** @description Must be credited wherever the photo is shown */
                photographer: string;
                /** @description Photo page on Planespotters.net, which the photo must link to */
                link: string;
              } | null;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Error message */
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Recommendation: {
      name: string;
      author: string;
      description: string;
      reason: string;
      amazonLink: string;
    };
    Recipe: {
      /**
       * Format: uuid
       * @description Recipe UUID
       */
      uuid: string;
      /** @description Recipe name */
      name: string;
      /** @description Recipe description */
      description: string;
      /** @description Recipe images */
      images: components['schemas']['Image'][];
      /** @description Recipe components */
      components: components['schemas']['Component'][];
    };
    Image: {
      /** @description Image timestamp */
      timestamp: number;
      /** @description S3 object key */
      key: string;
      /**
       * Format: uri
       * @description Presigned URL for downloading the image (undefined if generation failed)
       */
      presignedUrl?: string;
    };
    Component: {
      /** @description Component name */
      name: string;
      /**
       * Format: uuid
       * @description Component UUID
       */
      uuid: string;
      /** @description List of ingredients */
      ingredients: components['schemas']['Ingredient'][];
      /** @description List of instructions */
      instructions: components['schemas']['Instruction'][];
      /** @description Whether component can be made ahead */
      storeable?: boolean;
      /** @description Number of servings */
      servings?: number;
    };
    Ingredient: {
      /** @description Ingredient name */
      name: string;
      quantity: components['schemas']['Quantity'];
    };
    Quantity: {
      /**
       * @description Unit of measurement
       * @enum {string}
       */
      unit: 'none' | 'mL' | 'L' | 'g' | 'kg' | 'cup' | 'tsp' | 'tbsp' | 'quantity';
      /** @description Numeric value */
      value?: number;
    };
    Instruction: {
      /** @description Instruction text */
      text: string;
      /** @description Whether this step is optional */
      optional?: boolean;
    };
    MealPlan: components['schemas']['MealPlanDayEntry'][];
    MealPlanDayEntry: {
      /** @description Unix timestamp in milliseconds */
      date: number;
      /** @description Recipes for this day */
      plan: components['schemas']['MealPlanRecipe'][];
    };
    MealPlanRecipe: {
      /**
       * Format: uuid
       * @description Recipe UUID
       */
      recipeId: string;
      /** @description Recipe components */
      components: components['schemas']['MealPlanComponent'][];
    };
    MealPlanComponent: {
      /**
       * Format: uuid
       * @description Recipe component UUID
       */
      componentId: string;
      /** @description Number of servings */
      servings: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
